// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Settings.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Settings.Infrastructure.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    partial class SettingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.Setting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("00000000-0000-0000-0000-000000000001");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("00000000-0000-0000-0000-000000000001");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsReadOnly");

                    b.HasIndex("IsActive", "IsReadOnly");

                    b.HasIndex("CategoryId", "IsActive", "DisplayOrder");

                    b.ToTable("Settings", "settings");
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.SettingChangeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("00000000-0000-0000-0000-000000000001");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("00000000-0000-0000-0000-000000000001");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("SettingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SettingId");

                    b.HasIndex("ChangedByUserId", "CreatedAt");

                    b.HasIndex("SettingId", "CreatedAt");

                    b.HasIndex("SettingId", "ChangedByUserId", "CreatedAt");

                    b.ToTable("SettingChangeEvents", "settings");
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.SettingsCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SectionId");

                    b.HasIndex("SectionId", "Name")
                        .IsUnique();

                    b.HasIndex("SectionId", "IsActive", "DisplayOrder");

                    b.ToTable("SettingsCategories", "settings");
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.SettingsSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("SettingsSections", "settings");
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.Setting", b =>
                {
                    b.HasOne("Nezam.Refahi.Settings.Domain.Entities.SettingsCategory", "Category")
                        .WithMany("Settings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Settings.Domain.ValueObjects.SettingKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("SettingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Key");

                            b1.HasKey("SettingId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Settings", "settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingId");
                        });

                    b.OwnsOne("Nezam.Refahi.Settings.Domain.ValueObjects.SettingValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("SettingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("RawValue")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("Value");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ValueType");

                            b1.HasKey("SettingId");

                            b1.HasIndex("Type");

                            b1.ToTable("Settings", "settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.SettingChangeEvent", b =>
                {
                    b.HasOne("Nezam.Refahi.Settings.Domain.Entities.Setting", "Setting")
                        .WithMany("ChangeEvents")
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Settings.Domain.ValueObjects.SettingValue", "NewValue", b1 =>
                        {
                            b1.Property<Guid>("SettingChangeEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("RawValue")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("NewValue");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("NewValueType");

                            b1.HasKey("SettingChangeEventId");

                            b1.HasIndex("Type");

                            b1.ToTable("SettingChangeEvents", "settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingChangeEventId");
                        });

                    b.OwnsOne("Nezam.Refahi.Settings.Domain.ValueObjects.SettingValue", "OldValue", b1 =>
                        {
                            b1.Property<Guid>("SettingChangeEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("RawValue")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("OldValue");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("OldValueType");

                            b1.HasKey("SettingChangeEventId");

                            b1.HasIndex("Type");

                            b1.ToTable("SettingChangeEvents", "settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingChangeEventId");
                        });

                    b.OwnsOne("Nezam.Refahi.Settings.Domain.ValueObjects.SettingKey", "SettingKey", b1 =>
                        {
                            b1.Property<Guid>("SettingChangeEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SettingKey");

                            b1.HasKey("SettingChangeEventId");

                            b1.HasIndex("Value");

                            b1.ToTable("SettingChangeEvents", "settings");

                            b1.WithOwner()
                                .HasForeignKey("SettingChangeEventId");
                        });

                    b.Navigation("NewValue")
                        .IsRequired();

                    b.Navigation("OldValue")
                        .IsRequired();

                    b.Navigation("Setting");

                    b.Navigation("SettingKey")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.SettingsCategory", b =>
                {
                    b.HasOne("Nezam.Refahi.Settings.Domain.Entities.SettingsSection", "Section")
                        .WithMany("Categories")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.Setting", b =>
                {
                    b.Navigation("ChangeEvents");
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.SettingsCategory", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Nezam.Refahi.Settings.Domain.Entities.SettingsSection", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
