// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Facilities.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Facilities.Infrastructure.Migrations
{
    [DbContext(typeof(FacilitiesDbContext))]
    partial class FacilitiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("facilities")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Facilities", "facilities");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("InterestRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PaymentMonths")
                        .HasColumnType("int");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<bool>("RestrictToPreviousCycles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsedQuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("FacilityId");

                    b.HasIndex("Name");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.HasIndex("FacilityId", "StartDate", "EndDate");

                    b.ToTable("FacilityCycles", "facilities");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycleCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("FacilityCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("FacilityCycleId");

                    b.HasIndex("FacilityCycleId", "CapabilityId")
                        .IsUnique();

                    b.ToTable("FacilityCycleCapabilities", "facilities");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycleDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("MustBeCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("RequiredFacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequiredFacilityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("FacilityCycleId");

                    b.HasIndex("RequiredFacilityId");

                    b.HasIndex("CycleId", "RequiredFacilityId")
                        .IsUnique();

                    b.ToTable("FacilityCycleDependencies", "facilities", t =>
                        {
                            t.HasCheckConstraint("CK_FacilityCycleDependencies_CycleId_NotEqual_RequiredFacilityId", "CycleId != RequiredFacilityId");
                        });
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycleFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityCycleId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("FacilityCycleId", "FeatureId")
                        .IsUnique();

                    b.ToTable("FacilityCycleFeatures", "facilities");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCyclePriceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("FacilityCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("FacilityCycleId");

                    b.HasIndex("FacilityCycleId", "DisplayOrder");

                    b.ToTable("FacilityCyclePriceOptions", "facilities");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityRejection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RejectedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectedByUserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RejectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RejectedAt");

                    b.HasIndex("RejectedByUserId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("FacilityRejections", "facilities");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BankAppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BankAppointmentReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("BankAppointmentScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DisbursedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisbursementReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DispatchedToBankAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FacilityCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicySnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedByBankAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("SelectedPriceOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserNationalId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedAt");

                    b.HasIndex("BankAppointmentDate");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FacilityCycleId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("MemberId");

                    b.HasIndex("RejectionId");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasFilter("[RequestNumber] IS NOT NULL");

                    b.HasIndex("SelectedPriceOptionId");

                    b.HasIndex("Status");

                    b.ToTable("FacilityRequests", "facilities");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", b =>
                {
                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.Facility", "Facility")
                        .WithMany("Cycles")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycleCapability", b =>
                {
                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", "FacilityCycle")
                        .WithMany("Capabilities")
                        .HasForeignKey("FacilityCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityCycle");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycleDependency", b =>
                {
                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", "FacilityCycle")
                        .WithMany()
                        .HasForeignKey("FacilityCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityCycle");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycleFeature", b =>
                {
                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", "FacilityCycle")
                        .WithMany("Features")
                        .HasForeignKey("FacilityCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityCycle");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCyclePriceOption", b =>
                {
                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", "FacilityCycle")
                        .WithMany("PriceOptions")
                        .HasForeignKey("FacilityCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FacilityCyclePriceOptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountRials");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("IRR")
                                .HasColumnName("Currency");

                            b1.HasKey("FacilityCyclePriceOptionId");

                            b1.ToTable("FacilityCyclePriceOptions", "facilities");

                            b1.WithOwner()
                                .HasForeignKey("FacilityCyclePriceOptionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("FacilityCycle");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityRejection", b =>
                {
                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.FacilityRequest", "Request")
                        .WithOne()
                        .HasForeignKey("Nezam.Refahi.Facilities.Domain.Entities.FacilityRejection", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityRequest", b =>
                {
                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", "FacilityCycle")
                        .WithMany("Applications")
                        .HasForeignKey("FacilityCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Facilities.Domain.Entities.FacilityRejection", null)
                        .WithMany()
                        .HasForeignKey("RejectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "ApprovedAmount", b1 =>
                        {
                            b1.Property<Guid>("FacilityRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ApprovedAmountRials");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("IRR")
                                .HasColumnName("ApprovedCurrency");

                            b1.HasKey("FacilityRequestId");

                            b1.ToTable("FacilityRequests", "facilities");

                            b1.WithOwner()
                                .HasForeignKey("FacilityRequestId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "RequestedAmount", b1 =>
                        {
                            b1.Property<Guid>("FacilityRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("RequestedAmountRials");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("IRR")
                                .HasColumnName("RequestedCurrency");

                            b1.HasKey("FacilityRequestId");

                            b1.ToTable("FacilityRequests", "facilities");

                            b1.WithOwner()
                                .HasForeignKey("FacilityRequestId");
                        });

                    b.Navigation("ApprovedAmount");

                    b.Navigation("Facility");

                    b.Navigation("FacilityCycle");

                    b.Navigation("RequestedAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.Facility", b =>
                {
                    b.Navigation("Cycles");
                });

            modelBuilder.Entity("Nezam.Refahi.Facilities.Domain.Entities.FacilityCycle", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Capabilities");

                    b.Navigation("Dependencies");

                    b.Navigation("Features");

                    b.Navigation("PriceOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
