// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Identity.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20250902141206_UpdateSomeFields")]
    partial class UpdateSomeFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptsLeft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DeliveryStatus");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LockReason")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("ResendLeft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ChallengeStatus");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId")
                        .IsUnique()
                        .HasDatabaseName("IX_OtpChallenges_ChallengeId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_OtpChallenges_CreatedAt");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_OtpChallenges_ExpiresAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_OtpChallenges_Status");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("IX_OtpChallenges_Status_ExpiresAt");

                    b.ToTable("OtpChallenges", "identity");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rotation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_RefreshSessions_ClientId");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("IX_RefreshSessions_LastUsedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshSessions_UserId");

                    b.HasIndex("UserId", "ClientId")
                        .HasDatabaseName("IX_RefreshSessions_UserId_ClientId");

                    b.ToTable("RefreshSessions", (string)null);
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AccessCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastAccessedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("IX_Roles_DisplayOrder");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Roles_IsActive");

                    b.HasIndex("IsSystemRole")
                        .HasDatabaseName("IX_Roles_IsSystemRole");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_Roles_IsActive_DisplayOrder");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.RoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_RoleClaims_RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AccessCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastAccessedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAuthenticatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastUserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PhoneVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UnlockAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsPhoneVerified");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.UserClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("IX_UserClaims_AssignedAt");

                    b.HasIndex("AssignedBy")
                        .HasDatabaseName("IX_UserClaims_AssignedBy");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UserClaims_ExpiresAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UserClaims_IsActive");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserClaims_UserId");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("IX_UserClaims_IsActive_ExpiresAt");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_UserClaims_UserId_IsActive");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Category")
                        .HasDatabaseName("IX_UserPreferences_UserId_Category");

                    b.ToTable("UserPreferences", "identity");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("IX_UserRoles_AssignedAt");

                    b.HasIndex("AssignedBy")
                        .HasDatabaseName("IX_UserRoles_AssignedBy");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UserRoles_ExpiresAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UserRoles_IsActive");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserRoles_UserId");

                    b.HasIndex("IsActive", "ExpiresAt")
                        .HasDatabaseName("IX_UserRoles_IsActive_ExpiresAt");

                    b.HasIndex("RoleId", "IsActive")
                        .HasDatabaseName("IX_UserRoles_RoleId_IsActive");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_UserRoles_UserId_IsActive");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserRoles_UserId_RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsRevoked", "IsUsed")
                        .HasFilter("[IsRevoked] = 0 AND [IsUsed] = 0");

                    b.HasIndex("TokenValue", "TokenType")
                        .IsUnique();

                    SqlServerIndexBuilderExtensions.HasFillFactor(b.HasIndex("TokenValue", "TokenType"), 90);

                    b.HasIndex("UserId", "TokenType");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.OtpChallenge", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.DeviceFingerprint", "DeviceFingerprint", b1 =>
                        {
                            b1.Property<Guid>("OtpChallengeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasDefaultValue("")
                                .HasColumnName("DeviceFingerprint");

                            b1.HasKey("OtpChallengeId");

                            b1.ToTable("OtpChallenges", "identity");

                            b1.WithOwner()
                                .HasForeignKey("OtpChallengeId");
                        });

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("OtpChallengeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("OtpChallengeId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_OtpChallenges_PhoneNumber");

                            b1.ToTable("OtpChallenges", "identity");

                            b1.WithOwner()
                                .HasForeignKey("OtpChallengeId");
                        });

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.ClientId", "ClientId", b1 =>
                        {
                            b1.Property<Guid>("OtpChallengeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ClientId");

                            b1.HasKey("OtpChallengeId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_OtpChallenges_ClientId");

                            b1.ToTable("OtpChallenges", "identity");

                            b1.WithOwner()
                                .HasForeignKey("OtpChallengeId");
                        });

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.IpAddress", "IpAddress", b1 =>
                        {
                            b1.Property<Guid>("OtpChallengeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)")
                                .HasColumnName("IpAddress");

                            b1.HasKey("OtpChallengeId");

                            b1.ToTable("OtpChallenges", "identity");

                            b1.WithOwner()
                                .HasForeignKey("OtpChallengeId");
                        });

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.OtpPolicy", "Policy", b1 =>
                        {
                            b1.Property<Guid>("OtpChallengeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Length")
                                .HasColumnType("int")
                                .HasColumnName("OtpLength");

                            b1.Property<int>("MaxPerIpPerHour")
                                .HasColumnType("int")
                                .HasColumnName("MaxPerIpPerHour");

                            b1.Property<int>("MaxPerPhonePerHour")
                                .HasColumnType("int")
                                .HasColumnName("MaxPerPhonePerHour");

                            b1.Property<int>("MaxResends")
                                .HasColumnType("int")
                                .HasColumnName("MaxResends");

                            b1.Property<int>("MaxVerifyAttempts")
                                .HasColumnType("int")
                                .HasColumnName("MaxVerifyAttempts");

                            b1.Property<int>("TtlSeconds")
                                .HasColumnType("int")
                                .HasColumnName("TtlSeconds");

                            b1.HasKey("OtpChallengeId");

                            b1.ToTable("OtpChallenges", "identity");

                            b1.WithOwner()
                                .HasForeignKey("OtpChallengeId");
                        });

                    b.Navigation("ClientId")
                        .IsRequired();

                    b.Navigation("DeviceFingerprint");

                    b.Navigation("IpAddress");

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("Policy")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.RefreshSession", b =>
                {
                    b.HasOne("Nezam.Refahi.Identity.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.DeviceFingerprint", "DeviceFingerprint", b1 =>
                        {
                            b1.Property<Guid>("RefreshSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("DeviceFingerprintValue");

                            b1.HasKey("RefreshSessionId");

                            b1.ToTable("RefreshSessions");

                            b1.WithOwner()
                                .HasForeignKey("RefreshSessionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.HashedSecret", "CurrentTokenHash", b1 =>
                        {
                            b1.Property<Guid>("RefreshSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("TokenAlgorithm");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("TokenHash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("TokenSalt");

                            b1.HasKey("RefreshSessionId");

                            b1.ToTable("RefreshSessions");

                            b1.WithOwner()
                                .HasForeignKey("RefreshSessionId");
                        });

                    b.Navigation("CurrentTokenHash")
                        .IsRequired();

                    b.Navigation("DeviceFingerprint");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.RoleClaim", b =>
                {
                    b.HasOne("Nezam.Refahi.Identity.Domain.Entities.Role", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.Claim", "Claim", b1 =>
                        {
                            b1.Property<Guid>("RoleClaimId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ClaimType");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("ClaimValue");

                            b1.Property<string>("ValueType")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ClaimValueType");

                            b1.HasKey("RoleClaimId");

                            b1.HasIndex("Type")
                                .HasDatabaseName("IX_RoleClaims_ClaimType");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_RoleClaims_ClaimValue");

                            b1.ToTable("RoleClaims", "identity");

                            b1.WithOwner()
                                .HasForeignKey("RoleClaimId");
                        });

                    b.Navigation("Claim")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.DeviceFingerprint", "LastDeviceFingerprint", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasDefaultValue("")
                                .HasColumnName("LastDeviceFingerprint");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.NationalId", "NationalId", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NationalId");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[NationalId] IS NOT NULL");

                            b1.ToTable("Users", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("LastDeviceFingerprint");

                    b.Navigation("NationalId");

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.UserClaim", b =>
                {
                    b.HasOne("Nezam.Refahi.Identity.Domain.Entities.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.Claim", "Claim", b1 =>
                        {
                            b1.Property<Guid>("UserClaimId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ClaimType");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("ClaimValue");

                            b1.Property<string>("ValueType")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ClaimValueType");

                            b1.HasKey("UserClaimId");

                            b1.HasIndex("Type")
                                .HasDatabaseName("IX_UserClaims_ClaimType");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_UserClaims_ClaimValue");

                            b1.ToTable("UserClaims", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserClaimId");
                        });

                    b.Navigation("Claim")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("Nezam.Refahi.Identity.Domain.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.PreferenceKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("UserPreferenceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Key");

                            b1.HasKey("UserPreferenceId");

                            b1.ToTable("UserPreferences", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserPreferenceId");
                        });

                    b.OwnsOne("Nezam.Refahi.Identity.Domain.ValueObjects.PreferenceValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("UserPreferenceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("RawValue")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("Value");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("ValueType");

                            b1.HasKey("UserPreferenceId");

                            b1.HasIndex("Type")
                                .HasDatabaseName("IX_UserPreferences_ValueType");

                            b1.ToTable("UserPreferences", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserPreferenceId");
                        });

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Nezam.Refahi.Identity.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Identity.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("Nezam.Refahi.Identity.Domain.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.Role", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Nezam.Refahi.Identity.Domain.Entities.User", b =>
                {
                    b.Navigation("Preferences");

                    b.Navigation("Tokens");

                    b.Navigation("UserClaims");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
