// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Shared.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251006132137_AddOutboxEnhancements")]
    partial class AddOutboxEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shared")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Shared.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DlqReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FullTypeName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPoisonMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<DateTime?>("MovedToDlqAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PoisonedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SchemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("IX_OutboxMessages_AggregateId")
                        .HasFilter("[AggregateId] IS NOT NULL");

                    b.HasIndex("AssemblyName")
                        .HasDatabaseName("IX_OutboxMessages_AssemblyName");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_OutboxMessages_CorrelationId")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("FullTypeName")
                        .HasDatabaseName("IX_OutboxMessages_FullTypeName");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("IX_OutboxMessages_IdempotencyKey")
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("IsPoisonMessage")
                        .HasDatabaseName("IX_OutboxMessages_IsPoisonMessage");

                    b.HasIndex("MovedToDlqAt")
                        .HasDatabaseName("IX_OutboxMessages_MovedToDlqAt")
                        .HasFilter("[MovedToDlqAt] IS NOT NULL");

                    b.HasIndex("NextRetryAt")
                        .HasDatabaseName("IX_OutboxMessages_NextRetryAt")
                        .HasFilter("[NextRetryAt] IS NOT NULL");

                    b.HasIndex("OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_OccurredOn");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("IX_OutboxMessages_ProcessedOn");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_OutboxMessages_Type");

                    b.HasIndex("AggregateId", "OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_AggregateId_OccurredOn")
                        .HasFilter("[AggregateId] IS NOT NULL");

                    b.HasIndex("CorrelationId", "OccurredOn")
                        .HasDatabaseName("IX_OutboxMessages_CorrelationId_OccurredOn")
                        .HasFilter("[CorrelationId] IS NOT NULL");

                    b.HasIndex("ProcessedOn", "RetryCount")
                        .HasDatabaseName("IX_OutboxMessages_ProcessedOn_RetryCount");

                    b.HasIndex("Type", "ProcessedOn", "RetryCount")
                        .HasDatabaseName("IX_OutboxMessages_Type_ProcessedOn_RetryCount");

                    b.ToTable("OutboxMessages", "shared");
                });

            modelBuilder.Entity("Nezam.Refahi.Shared.Domain.Services.EventIdempotency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("IX_EventIdempotencies_AggregateId")
                        .HasFilter("[AggregateId] IS NOT NULL");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_EventIdempotencies_IdempotencyKey");

                    b.HasIndex("IsProcessed")
                        .HasDatabaseName("IX_EventIdempotencies_IsProcessed");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("IX_EventIdempotencies_ProcessedAt");

                    b.ToTable("EventIdempotencies", "shared");
                });
#pragma warning restore 612, 618
        }
    }
}
