// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Finance.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Finance.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20250924051112_AddWallletModelsToFinanacial")]
    partial class AddWallletModelsToFinanacial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FullyPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserNationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillNumber")
                        .IsUnique();

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Bill_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Bill_CreatedBy");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Bill_DeletedAt")
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("IX_Bill_DeletedBy")
                        .HasFilter("[DeletedBy] IS NOT NULL");

                    b.HasIndex("DueDate");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Bill_IsDeleted");

                    b.HasIndex("IssueDate");

                    b.HasIndex("LastModifiedAt")
                        .HasDatabaseName("IX_Bill_LastModifiedAt")
                        .HasFilter("[LastModifiedAt] IS NOT NULL");

                    b.HasIndex("LastModifiedBy")
                        .HasDatabaseName("IX_Bill_LastModifiedBy")
                        .HasFilter("[LastModifiedBy] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("UserNationalNumber");

                    b.HasIndex("ReferenceId", "BillType");

                    b.ToTable("Bills", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.BillItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("BillItems", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("BillNumber");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Payment_DeletedAt")
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("IX_Payment_DeletedBy")
                        .HasFilter("[DeletedBy] IS NOT NULL");

                    b.HasIndex("GatewayTransactionId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Payment_IsDeleted");

                    b.HasIndex("Status");

                    b.ToTable("Payments", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GatewayTransactionId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("Status");

                    b.ToTable("PaymentTransactions", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayRefundId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessorNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedByNationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("GatewayRefundId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedByNationalNumber");

                    b.HasIndex("Status");

                    b.ToTable("Refunds", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastTransactionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("WalletName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Wallet_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Wallet_CreatedBy");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Wallet_DeletedAt")
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("IX_Wallet_DeletedBy")
                        .HasFilter("[DeletedBy] IS NOT NULL");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Wallet_IsDeleted");

                    b.HasIndex("LastModifiedAt")
                        .HasDatabaseName("IX_Wallet_LastModifiedAt")
                        .HasFilter("[LastModifiedAt] IS NOT NULL");

                    b.HasIndex("LastModifiedBy")
                        .HasDatabaseName("IX_Wallet_LastModifiedBy")
                        .HasFilter("[LastModifiedBy] IS NOT NULL");

                    b.HasIndex("LastTransactionAt");

                    b.HasIndex("NationalNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("NationalNumber", "Status");

                    b.ToTable("Wallets", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletDeposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserNationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("IX_WalletDeposits_ExternalReference");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_WalletDeposits_RequestedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WalletDeposits_Status");

                    b.HasIndex("UserNationalNumber")
                        .HasDatabaseName("IX_WalletDeposits_UserNationalNumber");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("IX_WalletDeposits_WalletId");

                    b.HasIndex("UserNationalNumber", "RequestedAt")
                        .HasDatabaseName("IX_WalletDeposits_UserNationalNumber_RequestedAt");

                    b.HasIndex("WalletId", "Status")
                        .HasDatabaseName("IX_WalletDeposits_WalletId_Status");

                    b.ToTable("WalletDeposits", "Finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastTransactionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithdrawals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.Property<string>("UserNationalNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WalletId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("IX_WalletSnapshots_SnapshotDate");

                    b.HasIndex("UserNationalNumber")
                        .HasDatabaseName("IX_WalletSnapshots_UserNationalNumber");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("IX_WalletSnapshots_WalletId");

                    b.HasIndex("WalletId1");

                    b.HasIndex("UserNationalNumber", "SnapshotDate")
                        .HasDatabaseName("IX_WalletSnapshots_UserNationalNumber_SnapshotDate");

                    b.HasIndex("WalletId", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("IX_WalletSnapshots_WalletId_SnapshotDate");

                    b.ToTable("WalletSnapshots", "Finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalReference");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("TransactionType");

                    b.HasIndex("WalletId");

                    b.HasIndex("TransactionType", "CreatedAt");

                    b.HasIndex("WalletId", "CreatedAt");

                    b.HasIndex("WalletId", "TransactionType");

                    b.ToTable("WalletTransactions", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Bill", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "PaidAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PaidAmountRials");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "RemainingAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("RemainingAmountRials");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalAmountRials");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.Navigation("PaidAmount")
                        .IsRequired();

                    b.Navigation("RemainingAmount")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.BillItem", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "LineTotal", b1 =>
                        {
                            b1.Property<Guid>("BillItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("LineTotalRials");

                            b1.HasKey("BillItemId");

                            b1.ToTable("BillItems", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillItemId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("BillItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnitPriceRials");

                            b1.HasKey("BillItemId");

                            b1.ToTable("BillItems", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillItemId");
                        });

                    b.Navigation("Bill");

                    b.Navigation("LineTotal")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountRials");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "ProcessedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ProcessedAmountRials");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.Navigation("Payment");

                    b.Navigation("ProcessedAmount");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Refund", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Bill", "Bill")
                        .WithMany("Refunds")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RefundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountRials");

                            b1.HasKey("RefundId");

                            b1.ToTable("Refunds", "finance");

                            b1.WithOwner()
                                .HasForeignKey("RefundId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletDeposit", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletSnapshot", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Wallet", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("WalletId1");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("WalletTransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountRials");

                            b1.HasKey("WalletTransactionId");

                            b1.ToTable("WalletTransactions", "finance");

                            b1.WithOwner()
                                .HasForeignKey("WalletTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "BalanceAfter", b1 =>
                        {
                            b1.Property<Guid>("WalletTransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BalanceAfterRials");

                            b1.HasKey("WalletTransactionId");

                            b1.ToTable("WalletTransactions", "finance");

                            b1.WithOwner()
                                .HasForeignKey("WalletTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("BalanceAfter")
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Snapshots");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
