// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Finance.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Finance.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20251027144517_RemvoeTrackingCodes")]
    partial class RemvoeTrackingCodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("DiscountCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExternalUserId")
                        .HasMaxLength(10)
                        .HasColumnType("uniqueidentifier")
                        .IsFixedLength();

                    b.Property<DateTime?>("FullyPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceTrackCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("sdad");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ReferenceType");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillNumber")
                        .IsUnique();

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Bill_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Bill_CreatedBy");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Bill_DeletedAt")
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("IX_Bill_DeletedBy")
                        .HasFilter("[DeletedBy] IS NOT NULL");

                    b.HasIndex("DueDate");

                    b.HasIndex("ExternalUserId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Bill_IsDeleted");

                    b.HasIndex("IssueDate");

                    b.HasIndex("LastModifiedAt")
                        .HasDatabaseName("IX_Bill_LastModifiedAt")
                        .HasFilter("[LastModifiedAt] IS NOT NULL");

                    b.HasIndex("LastModifiedBy")
                        .HasDatabaseName("IX_Bill_LastModifiedBy")
                        .HasFilter("[LastModifiedBy] IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("ReferenceId", "ReferenceType");

                    b.ToTable("Bills", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.BillItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("BillItems", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.DiscountCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("کد تخفیف");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("تاریخ ایجاد");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("ایجادکننده");

                    b.Property<Guid?>("CreatedByExternalUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("شناسه کاربر ایجادکننده");

                    b.Property<string>("CreatedByUserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("نام کامل کاربر ایجادکننده");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasComment("تاریخ حذف");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("حذف‌کننده");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("توضیحات کد تخفیف");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("مقدار تخفیف");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("آیا فعال است");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("آیا حذف شده");

                    b.Property<bool>("IsSingleUse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("آیا یکبار مصرف است");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasComment("تاریخ آخرین تغییر");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("آخرین تغییردهنده");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("اطلاعات اضافی");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("وضعیت کد تخفیف");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("عنوان کد تخفیف");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("نوع تخفیف (درصدی یا مبلغی)");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int")
                        .HasComment("حد مجاز استفاده");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("تعداد استفاده شده");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2")
                        .HasComment("تاریخ شروع اعتبار");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime2")
                        .HasComment("تاریخ پایان اعتبار");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_DiscountCodes_Code");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DiscountCodes_Status");

                    b.HasIndex("ValidFrom")
                        .HasDatabaseName("IX_DiscountCodes_ValidFrom");

                    b.HasIndex("ValidTo")
                        .HasDatabaseName("IX_DiscountCodes_ValidTo");

                    b.HasIndex("Status", "ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_DiscountCodes_Status_ValidDates");

                    b.ToTable("DiscountCodes", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.DiscountCodeUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("شناسه فاکتور");

                    b.Property<Guid>("DiscountCodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("شناسه کد تخفیف");

                    b.Property<Guid>("DiscountCodeId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExternalUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("شناسه کاربر");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("اطلاعات اضافی");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("یادداشت‌ها");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasComment("تاریخ استفاده");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("نام کامل کاربر");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .HasDatabaseName("IX_DiscountCodeUsages_BillId");

                    b.HasIndex("DiscountCodeId")
                        .HasDatabaseName("IX_DiscountCodeUsages_DiscountCodeId");

                    b.HasIndex("DiscountCodeId1");

                    b.HasIndex("ExternalUserId")
                        .HasDatabaseName("IX_DiscountCodeUsages_ExternalUserId");

                    b.HasIndex("UsedAt")
                        .HasDatabaseName("IX_DiscountCodeUsages_UsedAt");

                    b.HasIndex("DiscountCodeId", "BillId")
                        .HasDatabaseName("IX_DiscountCodeUsages_DiscountCodeId_BillId");

                    b.HasIndex("DiscountCodeId", "ExternalUserId")
                        .HasDatabaseName("IX_DiscountCodeUsages_DiscountCodeId_ExternalUserId");

                    b.ToTable("DiscountCodeUsages", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppliedDiscountCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("AppliedDiscountCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFreePayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Payment_DeletedAt")
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("IX_Payment_DeletedBy")
                        .HasFilter("[DeletedBy] IS NOT NULL");

                    b.HasIndex("GatewayReference");

                    b.HasIndex("GatewayTransactionId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Payment_IsDeleted");

                    b.HasIndex("Status");

                    b.ToTable("Payments", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GatewayTransactionId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("Status");

                    b.ToTable("PaymentTransactions", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GatewayRefundId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessorNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedByExternalUserId")
                        .HasMaxLength(10)
                        .HasColumnType("uniqueidentifier")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("GatewayRefundId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedByExternalUserId");

                    b.HasIndex("Status");

                    b.ToTable("Refunds", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ExternalUserId")
                        .HasMaxLength(10)
                        .HasColumnType("uniqueidentifier")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastTransactionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("WalletName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Wallet_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Wallet_CreatedBy");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Wallet_DeletedAt")
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("IX_Wallet_DeletedBy")
                        .HasFilter("[DeletedBy] IS NOT NULL");

                    b.HasIndex("ExternalUserId")
                        .IsUnique();

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Wallet_IsDeleted");

                    b.HasIndex("LastModifiedAt")
                        .HasDatabaseName("IX_Wallet_LastModifiedAt")
                        .HasFilter("[LastModifiedAt] IS NOT NULL");

                    b.HasIndex("LastModifiedBy")
                        .HasDatabaseName("IX_Wallet_LastModifiedBy")
                        .HasFilter("[LastModifiedBy] IS NOT NULL");

                    b.HasIndex("LastTransactionAt");

                    b.HasIndex("Status");

                    b.HasIndex("ExternalUserId", "Status");

                    b.ToTable("Wallets", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletDeposit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ExternalUserId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("IX_WalletDeposits_ExternalReference");

                    b.HasIndex("ExternalUserId")
                        .HasDatabaseName("IX_WalletDeposits_ExternalUserId");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("IX_WalletDeposits_RequestedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WalletDeposits_Status");

                    b.HasIndex("TrackingCode")
                        .IsUnique()
                        .HasDatabaseName("IX_WalletDeposits_TrackingCode");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("IX_WalletDeposits_WalletId");

                    b.HasIndex("ExternalUserId", "RequestedAt")
                        .HasDatabaseName("IX_WalletDeposits_ExternalUserId_RequestedAt");

                    b.HasIndex("WalletId", "Status")
                        .HasDatabaseName("IX_WalletDeposits_WalletId_Status");

                    b.ToTable("WalletDeposits", "Finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExternalUserId")
                        .HasMaxLength(20)
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastTransactionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithdrawals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId")
                        .HasDatabaseName("IX_WalletSnapshots_ExternalUserId");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("IX_WalletSnapshots_SnapshotDate");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("IX_WalletSnapshots_WalletId");

                    b.HasIndex("ExternalUserId", "SnapshotDate")
                        .HasDatabaseName("IX_WalletSnapshots_ExternalUserId_SnapshotDate");

                    b.HasIndex("WalletId", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("IX_WalletSnapshots_WalletId_SnapshotDate_Unique");

                    b.ToTable("WalletSnapshots", "Finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExternalReference");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("TransactionType");

                    b.HasIndex("WalletId");

                    b.HasIndex("TransactionType", "CreatedAt");

                    b.HasIndex("WalletId", "CreatedAt");

                    b.HasIndex("WalletId", "TransactionType");

                    b.ToTable("WalletTransactions", "finance");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Bill", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "DiscountAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DiscountAmountRials");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "PaidAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PaidAmountRials");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "RemainingAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("RemainingAmountRials");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalAmountRials");

                            b1.HasKey("BillId");

                            b1.ToTable("Bills", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.Navigation("DiscountAmount");

                    b.Navigation("PaidAmount")
                        .IsRequired();

                    b.Navigation("RemainingAmount")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.BillItem", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "LineTotal", b1 =>
                        {
                            b1.Property<Guid>("BillItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("LineTotalRials");

                            b1.HasKey("BillItemId");

                            b1.ToTable("BillItems", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillItemId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("BillItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnitPriceRials");

                            b1.HasKey("BillItemId");

                            b1.ToTable("BillItems", "finance");

                            b1.WithOwner()
                                .HasForeignKey("BillItemId");
                        });

                    b.Navigation("Bill");

                    b.Navigation("LineTotal")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.DiscountCode", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "MaximumDiscountAmount", b1 =>
                        {
                            b1.Property<Guid>("DiscountCodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MaximumDiscountAmountRials")
                                .HasComment("حداکثر مبلغ تخفیف");

                            b1.HasKey("DiscountCodeId");

                            b1.ToTable("DiscountCodes", "finance");

                            b1.WithOwner()
                                .HasForeignKey("DiscountCodeId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "MinimumBillAmount", b1 =>
                        {
                            b1.Property<Guid>("DiscountCodeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MinimumBillAmountRials")
                                .HasComment("حداقل مبلغ فاکتور");

                            b1.HasKey("DiscountCodeId");

                            b1.ToTable("DiscountCodes", "finance");

                            b1.WithOwner()
                                .HasForeignKey("DiscountCodeId");
                        });

                    b.Navigation("MaximumDiscountAmount");

                    b.Navigation("MinimumBillAmount");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.DiscountCodeUsage", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.DiscountCode", null)
                        .WithMany()
                        .HasForeignKey("DiscountCodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.DiscountCode", "DiscountCode")
                        .WithMany("Usages")
                        .HasForeignKey("DiscountCodeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "BillAmount", b1 =>
                        {
                            b1.Property<Guid>("DiscountCodeUsageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BillAmountRials")
                                .HasComment("مبلغ فاکتور");

                            b1.HasKey("DiscountCodeUsageId");

                            b1.ToTable("DiscountCodeUsages", "finance");

                            b1.WithOwner()
                                .HasForeignKey("DiscountCodeUsageId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "DiscountAmount", b1 =>
                        {
                            b1.Property<Guid>("DiscountCodeUsageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DiscountAmountRials")
                                .HasComment("مبلغ تخفیف");

                            b1.HasKey("DiscountCodeUsageId");

                            b1.ToTable("DiscountCodeUsages", "finance");

                            b1.WithOwner()
                                .HasForeignKey("DiscountCodeUsageId");
                        });

                    b.Navigation("BillAmount")
                        .IsRequired();

                    b.Navigation("DiscountAmount")
                        .IsRequired();

                    b.Navigation("DiscountCode");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountRials");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "AppliedDiscountAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AppliedDiscountAmountRials");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("AppliedDiscountAmount");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "ProcessedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ProcessedAmountRials");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions", "finance");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.Navigation("Payment");

                    b.Navigation("ProcessedAmount");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Refund", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Bill", "Bill")
                        .WithMany("Refunds")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RefundId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountRials");

                            b1.HasKey("RefundId");

                            b1.ToTable("Refunds", "finance");

                            b1.WithOwner()
                                .HasForeignKey("RefundId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletDeposit", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletSnapshot", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Snapshots")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Nezam.Refahi.Finance.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("WalletTransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AmountRials");

                            b1.HasKey("WalletTransactionId");

                            b1.ToTable("WalletTransactions", "finance");

                            b1.WithOwner()
                                .HasForeignKey("WalletTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.Money", "PreviousBalance", b1 =>
                        {
                            b1.Property<Guid>("WalletTransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("AmountRials")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PreviousBalanceRials");

                            b1.HasKey("WalletTransactionId");

                            b1.ToTable("WalletTransactions", "finance");

                            b1.WithOwner()
                                .HasForeignKey("WalletTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("PreviousBalance")
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Bill", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.DiscountCode", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Nezam.Refahi.Finance.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Snapshots");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
