// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250505120049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Aggregates.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastPaymentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LockExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PrimaryGuestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastPaymentTransactionId")
                        .HasFilter("[LastPaymentTransactionId] IS NOT NULL");

                    b.HasIndex("PrimaryGuestId");

                    b.HasIndex("Status");

                    b.HasIndex("HotelId", "Status");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("Name");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.HotelFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HotelId", "Name")
                        .IsUnique();

                    b.ToTable("HotelFeature");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.HotelPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMainPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url");

                    b.HasIndex("HotelId", "IsMainPhoto")
                        .IsUnique()
                        .HasFilter("\"IsMainPhoto\" = true");

                    b.ToTable("HotelPhoto");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalIdValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NationalIdValue");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Payment.Aggregates.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptureReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DisputeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DisputeResolutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeStatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InstallmentPlanId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RefundedTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalInstallments")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionReference");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Aggregates.Reservation", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", "Hotel")
                        .WithMany("Reservations")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Guest", "PrimaryGuest")
                        .WithMany()
                        .HasForeignKey("PrimaryGuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalPrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalPrice_Currency");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.DateRange", "StayPeriod", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("CheckIn")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckInDate");

                            b1.Property<DateOnly>("CheckOut")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckOutDate");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("Hotel");

                    b.Navigation("PrimaryGuest");

                    b.Navigation("StayPeriod")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Guest", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Aggregates.Reservation", null)
                        .WithMany("Guests")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Identity.ValueObjects.NationalId", "NationalId", b1 =>
                        {
                            b1.Property<Guid>("GuestId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("NationalId");

                            b1.HasKey("GuestId");

                            b1.ToTable("Guest");

                            b1.WithOwner()
                                .HasForeignKey("GuestId");
                        });

                    b.Navigation("NationalId")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "PricePerNight", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PricePerNight_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("PricePerNight_Currency");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.LocationReference", "Location", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address");

                            b1.Property<Guid>("CityId")
                                .HasColumnType("TEXT")
                                .HasColumnName("CityId");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("CityName");

                            b1.Property<Guid>("ProvinceId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvinceId");

                            b1.Property<string>("ProvinceName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvinceName");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("PricePerNight")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.HotelFeature", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", "Hotel")
                        .WithMany("Features")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.HotelPhoto", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", "Hotel")
                        .WithMany("Photos")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.City", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Payment.Aggregates.PaymentTransaction", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount_Value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount_Currency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "AuthorizedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorizedAmount_Value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorizedAmount_Currency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "CapturedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("CapturedAmount_Value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("CapturedAmount_Currency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "OriginalAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("OriginalAmount_Value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("OriginalAmount_Currency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "RefundFee", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("RefundFee_Value");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("RefundFee_Currency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("AuthorizedAmount");

                    b.Navigation("CapturedAmount");

                    b.Navigation("OriginalAmount");

                    b.Navigation("RefundFee");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Aggregates.Reservation", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Photos");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
