// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522121517_Update_20250522154513")]
    partial class Update_20250522154513
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Aggregates.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastPaymentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LockExpirationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PrimaryGuestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastPaymentTransactionId")
                        .HasFilter("[LastPaymentTransactionId] IS NOT NULL");

                    b.HasIndex("PrimaryGuestId");

                    b.HasIndex("Status");

                    b.HasIndex("HotelId", "Status");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.HasIndex("Name");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.HotelFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HotelId", "Name")
                        .IsUnique();

                    b.ToTable("HotelFeature");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.HotelPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMainPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url");

                    b.HasIndex("HotelId", "IsMainPhoto")
                        .IsUnique()
                        .HasFilter("\"IsMainPhoto\" = true");

                    b.ToTable("HotelPhoto");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Payment.Aggregates.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptureReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DisputeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DisputeResolutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisputeStatus")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InstallmentPlanId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefundReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RefundedTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalInstallments")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionReference");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosesAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OpensAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("OpensAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("CreatorId", "Status");

                    b.HasIndex("Status", "OpensAtUtc");

                    b.ToTable("Surveys", (string)null);
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResponseId");

                    b.HasIndex("QuestionId", "OptionId");

                    b.HasIndex("ResponseId", "QuestionId")
                        .IsUnique();

                    b.ToTable("SurveyAnswers", (string)null);
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyOptions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId", "DisplayOrder");

                    b.ToTable("SurveyOptions", (string)null);
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId", "Order");

                    b.HasIndex("SurveyId", "Type");

                    b.ToTable("SurveyQuestions", (string)null);
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TimedOut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ResponderId");

                    b.HasIndex("SubmittedAtUtc");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId", "ResponderId");

                    b.HasIndex("SurveyId", "SubmittedAtUtc");

                    b.HasIndex("SurveyId", "TimedOut");

                    b.ToTable("SurveyResponses", (string)null);
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Aggregates.Reservation", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", "Hotel")
                        .WithMany("Reservations")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Guest", "PrimaryGuest")
                        .WithMany()
                        .HasForeignKey("PrimaryGuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "TotalPrice", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalPriceCurrency");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.DateRange", "StayPeriod", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("TEXT");

                            b1.Property<DateOnly>("CheckIn")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckInDate");

                            b1.Property<DateOnly>("CheckOut")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckOutDate");

                            b1.HasKey("ReservationId");

                            b1.ToTable("Reservations");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId");
                        });

                    b.Navigation("Hotel");

                    b.Navigation("PrimaryGuest");

                    b.Navigation("StayPeriod")
                        .IsRequired();

                    b.Navigation("TotalPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Guest", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Aggregates.Reservation", null)
                        .WithMany("Guests")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Identity.ValueObjects.NationalId", "NationalId", b1 =>
                        {
                            b1.Property<Guid>("GuestId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("NationalId");

                            b1.HasKey("GuestId");

                            b1.ToTable("Guest");

                            b1.WithOwner()
                                .HasForeignKey("GuestId");
                        });

                    b.Navigation("NationalId")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "PricePerNight", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PricePerNight");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("PricePerNightCurrency");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.LocationReference", "Location", b1 =>
                        {
                            b1.Property<Guid>("HotelId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Address");

                            b1.Property<Guid>("CityId")
                                .HasColumnType("TEXT")
                                .HasColumnName("CityId");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("CityName");

                            b1.Property<Guid>("ProvinceId")
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvinceId");

                            b1.Property<string>("ProvinceName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ProvinceName");

                            b1.HasKey("HotelId");

                            b1.ToTable("Hotels");

                            b1.WithOwner()
                                .HasForeignKey("HotelId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("PricePerNight")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.HotelFeature", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", "Hotel")
                        .WithMany("Features")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.HotelPhoto", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", "Hotel")
                        .WithMany("Photos")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Identity.Entities.User", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Identity.ValueObjects.NationalId", "NationalId", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("NationalId");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("NationalId");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.City", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Payment.Aggregates.PaymentTransaction", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("AmountCurrency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "AuthorizedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorizedAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorizedAmountCurrency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "CapturedAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("CapturedAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("CapturedAmountCurrency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "OriginalAmount", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("OriginalAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("OriginalAmountCurrency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.OwnsOne("Nezam.Refahi.Domain.BoundedContexts.Accommodation.ValueObjects.Money", "RefundFee", b1 =>
                        {
                            b1.Property<Guid>("PaymentTransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("RefundFee");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("RefundFeeCurrency");

                            b1.HasKey("PaymentTransactionId");

                            b1.ToTable("PaymentTransactions");

                            b1.WithOwner()
                                .HasForeignKey("PaymentTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("AuthorizedAmount");

                    b.Navigation("CapturedAmount");

                    b.Navigation("OriginalAmount");

                    b.Navigation("RefundFee");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.Survey", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Identity.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyAnswer", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyOptions", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyResponse", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyOptions", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyQuestion", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Surveis.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyResponse", b =>
                {
                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Identity.Entities.User", "Responder")
                        .WithMany()
                        .HasForeignKey("ResponderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nezam.Refahi.Domain.BoundedContexts.Surveis.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responder");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Aggregates.Reservation", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Accommodation.Entities.Hotel", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Photos");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Location.Entities.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Nezam.Refahi.Domain.BoundedContexts.Surveis.SurveyResponse", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
