// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Surveying.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Surveys.Infrastructure.Migrations
{
    [DbContext(typeof(SurveyDbContext))]
    [Migration("20250928111558_FixQuestionAnswerRelationship")]
    partial class FixQuestionAnswerRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("surveying")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId", "Order");

                    b.ToTable("Questions", "surveying");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ResponseId");

                    b.HasIndex("ResponseId", "QuestionId")
                        .IsUnique();

                    b.ToTable("QuestionAnswers", "surveying");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.QuestionAnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuestionAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionAnswerId");

                    b.HasIndex("QuestionAnswerId", "OptionId")
                        .IsUnique();

                    b.ToTable("QuestionAnswerOptions", "surveying");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId", "Order");

                    b.ToTable("QuestionOptions", "surveying");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Response", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId", "AttemptNumber");

                    b.ToTable("Responses", "surveying");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("EndAt");

                    b.HasIndex("IsAnonymous");

                    b.HasIndex("StartAt");

                    b.HasIndex("State");

                    b.ToTable("Surveys", "surveying");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.SurveyCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapabilityKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CapabilityTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityKey");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId", "CapabilityKey")
                        .IsUnique();

                    b.ToTable("SurveyCapabilities", "surveying");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.SurveyFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FeatureTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FeatureKey");

                    b.HasIndex("SurveyId");

                    b.HasIndex("SurveyId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("SurveyFeatures", "surveying");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Question", b =>
                {
                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.Survey", null)
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.Response", "Response")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Response");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.QuestionAnswerOption", b =>
                {
                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.QuestionOption", null)
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.QuestionAnswer", null)
                        .WithMany("SelectedOptions")
                        .HasForeignKey("QuestionAnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Response", b =>
                {
                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.Survey", null)
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Nezam.Refahi.Surveying.Domain.ValueObjects.DemographySnapshot", "DemographySnapshot", b1 =>
                        {
                            b1.Property<Guid>("ResponseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("DemographyData");

                            b1.HasKey("ResponseId");

                            b1.ToTable("Responses", "surveying");

                            b1.WithOwner()
                                .HasForeignKey("ResponseId");
                        });

                    b.OwnsOne("Nezam.Refahi.Surveying.Domain.ValueObjects.ParticipantInfo", "Participant", b1 =>
                        {
                            b1.Property<Guid>("ResponseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FullName")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("FullName");

                            b1.Property<Guid?>("MemberId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("MemberId");

                            b1.Property<string>("NationalCode")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NationalCode");

                            b1.Property<string>("ParticipantHash")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ParticipantHash");

                            b1.HasKey("ResponseId");

                            b1.HasIndex("MemberId");

                            b1.HasIndex("ParticipantHash");

                            b1.ToTable("Responses", "surveying");

                            b1.WithOwner()
                                .HasForeignKey("ResponseId");
                        });

                    b.Navigation("DemographySnapshot");

                    b.Navigation("Participant")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Survey", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Surveying.Domain.ValueObjects.AudienceFilter", "AudienceFilter", b1 =>
                        {
                            b1.Property<Guid>("SurveyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FilterExpression")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("AudienceFilter");

                            b1.HasKey("SurveyId");

                            b1.ToTable("Surveys", "surveying");

                            b1.WithOwner()
                                .HasForeignKey("SurveyId");
                        });

                    b.OwnsOne("Nezam.Refahi.Surveying.Domain.ValueObjects.ParticipationPolicy", "ParticipationPolicy", b1 =>
                        {
                            b1.Property<Guid>("SurveyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("AllowMultipleSubmissions")
                                .HasColumnType("bit")
                                .HasColumnName("AllowMultipleSubmissions");

                            b1.Property<int?>("CoolDownSeconds")
                                .HasColumnType("int")
                                .HasColumnName("CoolDownSeconds");

                            b1.Property<int>("MaxAttemptsPerMember")
                                .HasColumnType("int")
                                .HasColumnName("MaxAttemptsPerMember");

                            b1.HasKey("SurveyId");

                            b1.ToTable("Surveys", "surveying");

                            b1.WithOwner()
                                .HasForeignKey("SurveyId");
                        });

                    b.Navigation("AudienceFilter");

                    b.Navigation("ParticipationPolicy")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.SurveyCapability", b =>
                {
                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.Survey", null)
                        .WithMany("SurveyCapabilities")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.SurveyFeature", b =>
                {
                    b.HasOne("Nezam.Refahi.Surveying.Domain.Entities.Survey", null)
                        .WithMany("SurveyFeatures")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.QuestionAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Response", b =>
                {
                    b.Navigation("QuestionAnswers");
                });

            modelBuilder.Entity("Nezam.Refahi.Surveying.Domain.Entities.Survey", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Responses");

                    b.Navigation("SurveyCapabilities");

                    b.Navigation("SurveyFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
