<#
.SYNOPSIS
    Deletes all data from database tables (WARNING: Destructive operation!)
    
.DESCRIPTION
    This script deletes all data from database tables while keeping the schema.
    Use with extreme caution as this operation cannot be undone.
    
.PARAMETER Context
    Specific DbContext to clean (default: all)
    
.PARAMETER Confirm
    Skip confirmation prompt (dangerous!)
#>

param(
    [string]$Context = "all",
    [switch]$Confirm
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$WebApiProject = Join-Path $ProjectRoot "src\Nezam.Refahi.WebApi\Nezam.Refahi.WebApi.csproj"

Write-Host "========================================" -ForegroundColor Red
Write-Host "WARNING: DESTRUCTIVE OPERATION" -ForegroundColor Red
Write-Host "========================================" -ForegroundColor Red
Write-Host "This script will DELETE ALL DATA from database tables!" -ForegroundColor Red
Write-Host "This operation CANNOT be undone!" -ForegroundColor Red
Write-Host ""

if (-not $Confirm) {
    $confirmation = Read-Host "Type 'DELETE ALL DATA' to confirm"
    if ($confirmation -ne "DELETE ALL DATA") {
        Write-Host "Operation cancelled." -ForegroundColor Yellow
        exit 0
    }
}

Write-Host ""
Write-Host "Deleting database data..." -ForegroundColor Yellow
Write-Host "Note: This requires manual SQL execution or a database cleanup script." -ForegroundColor Yellow
Write-Host ""

# Define table schemas for each context
$TableSchemas = @{
    "Identity" = @{
        Schema = "identity"
        Tables = @("AspNetUsers", "AspNetRoles", "AspNetUserRoles", "AspNetUserClaims", "AspNetRoleClaims", "AspNetUserLogins", "AspNetUserTokens")
    }
    "Membership" = @{
        Schema = "membership"
        Tables = @("Members", "MemberCapabilities", "MemberFeatures", "MemberDocuments")
    }
    "Facilities" = @{
        Schema = "facilities"
        Tables = @("Facilities", "FacilityCycles", "FacilityRequests", "FacilityCycleDependencies", "FacilityCyclePriceOptions", "FacilityCycleFeatures", "FacilityCycleCapabilities", "FacilityRejections")
    }
    "Settings" = @{
        Schema = "settings"
        Tables = @("Settings", "SettingCategories")
    }
    "BasicDefinitions" = @{
        Schema = "definitions"
        Tables = @("Capabilities", "Features", "Agencies")
    }
    "Surveying" = @{
        Schema = "surveys"
        Tables = @("Surveys", "SurveyQuestions", "SurveyResponses", "SurveyCapabilities")
    }
    "Finance" = @{
        Schema = "finance"
        Tables = @("Bills", "BillItems", "Payments", "Transactions")
    }
    "Recreation" = @{
        Schema = "recreation"
        Tables = @("Tours", "TourFeatures", "TourBookings", "Reservations")
    }
    "Notification" = @{
        Schema = "notifications"
        Tables = @("Notifications", "NotificationTemplates")
    }
}

# Get connection string from appsettings
$appsettingsPath = Join-Path $ProjectRoot "src\Nezam.Refahi.WebApi\appsettings.json"
$appsettings = Get-Content $appsettingsPath | ConvertFrom-Json
$connectionString = $appsettings.ConnectionStrings.DefaultConnection

if (-not $connectionString) {
    Write-Host "Error: Connection string not found in appsettings.json" -ForegroundColor Red
    exit 1
}

Write-Host "Connection: $connectionString" -ForegroundColor Cyan
Write-Host ""

# Generate SQL script to delete all data
$sqlScript = @"
-- SQL Script to delete all data from tables
-- Generated by delete-database-data.ps1
-- WARNING: This will delete ALL data!

"@

foreach ($schemaName in $TableSchemas.Keys) {
    if ($Context -eq "all" -or $Context -eq $schemaName) {
        $schema = $TableSchemas[$schemaName]
        $sqlScript += "`n-- $schemaName Schema`n"
        $sqlScript += "USE [Nezam.Refahi];`n"
        
        foreach ($table in $schema.Tables) {
            $fullTableName = "[$($schema.Schema)].[$table]"
            $sqlScript += "DELETE FROM $fullTableName;`n"
        }
        
        $sqlScript += "`n"
    }
}

$sqlScriptPath = Join-Path $ScriptDir "delete-all-data.sql"
$sqlScript | Out-File -FilePath $sqlScriptPath -Encoding UTF8

Write-Host "SQL script generated: $sqlScriptPath" -ForegroundColor Green
Write-Host ""
Write-Host "To execute the SQL script, run:" -ForegroundColor Yellow
Write-Host "  sqlcmd -S <server> -d Nezam.Refahi -i `"$sqlScriptPath`"" -ForegroundColor Cyan
Write-Host ""
Write-Host "Or use SQL Server Management Studio to execute the script." -ForegroundColor Yellow
Write-Host ""
Write-Host "Alternatively, you can drop and recreate the database using:" -ForegroundColor Yellow
Write-Host "  .\scripts\apply-all-migrations.ps1 -DeleteExistingData" -ForegroundColor Cyan

