// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Notifications.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Notifications.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250925100443_UpdateNotifaciatins")]
    partial class UpdateNotifaciatins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Notifications.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExternalUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_Notifications_Action");

                    b.HasIndex("Context")
                        .HasDatabaseName("IX_Notifications_Context");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Notifications_CreatedAt");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Notifications_ExpiresAt");

                    b.HasIndex("ExternalUserId")
                        .HasDatabaseName("IX_Notifications_ExternalUserId");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("IX_Notifications_IsRead");

                    b.HasIndex("ExternalUserId", "Action")
                        .HasDatabaseName("IX_Notifications_ExternalUserId_Action");

                    b.HasIndex("ExternalUserId", "Context")
                        .HasDatabaseName("IX_Notifications_ExternalUserId_Context");

                    b.HasIndex("ExternalUserId", "IsRead")
                        .HasDatabaseName("IX_Notifications_ExternalUserId_IsRead");

                    b.ToTable("Notifications", "notification");
                });
#pragma warning restore 612, 618
        }
    }
}
