// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nezam.Refahi.Membership.Infrastructure.Persistence;

#nullable disable

namespace Nezam.Refahi.Membership.Infrastructure.Migrations
{
    [DbContext(typeof(MembershipDbContext))]
    [Migration("20250927054016_UpdateTheNewChanges")]
    partial class UpdateTheNewChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Member_CreatedAt");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Member_CreatedBy");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_Member_DeletedAt")
                        .HasFilter("[DeletedAt] IS NOT NULL");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("IX_Member_DeletedBy")
                        .HasFilter("[DeletedBy] IS NOT NULL");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Member_IsDeleted");

                    b.HasIndex("LastModifiedAt")
                        .HasDatabaseName("IX_Member_LastModifiedAt")
                        .HasFilter("[LastModifiedAt] IS NOT NULL");

                    b.HasIndex("LastModifiedBy")
                        .HasDatabaseName("IX_Member_LastModifiedBy")
                        .HasFilter("[LastModifiedBy] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Members_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Members", "membership");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.MemberAgency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OfficeTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevel")
                        .HasDatabaseName("IX_MemberAgencies_AccessLevel");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("IX_MemberAgencies_AssignedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MemberAgencies_IsActive");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_MemberAgencies_MemberId");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("IX_MemberAgencies_AgencyId");

                    b.HasIndex("MemberId", "AgencyId")
                        .IsUnique()
                        .HasDatabaseName("IX_MemberAgencies_Member_Office_Active")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_MemberAgencies_ValidityPeriod");

                    b.ToTable("MemberAgencies", "membership");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.MemberCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CapabilityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAt")
                        .HasDatabaseName("IX_MemberCapabilities_AssignedAt");

                    b.HasIndex("CapabilityId")
                        .HasDatabaseName("IX_MemberCapabilities_CapabilityId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MemberCapabilities_IsActive");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_MemberCapabilities_MemberId");

                    b.HasIndex("MemberId", "CapabilityId")
                        .IsUnique()
                        .HasDatabaseName("IX_MemberCapabilities_Member_Capability_Active")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("ValidFrom", "ValidTo")
                        .HasDatabaseName("IX_MemberCapabilities_ValidityPeriod");

                    b.ToTable("MemberCapabilities", "membership");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.MemberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_MemberRoles_IsActive");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IX_MemberRoles_MemberId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_MemberRoles_RoleId");

                    b.HasIndex("ValidTo")
                        .HasDatabaseName("IX_MemberRoles_ValidTo");

                    b.HasIndex("MemberId", "IsActive")
                        .HasDatabaseName("IX_MemberRoles_Member_IsActive");

                    b.HasIndex("MemberId", "RoleId")
                        .HasDatabaseName("IX_MemberRoles_Member_Role");

                    b.HasIndex("MemberId", "ValidTo")
                        .HasDatabaseName("IX_MemberRoles_Member_ValidTo");

                    b.HasIndex("RoleId", "IsActive")
                        .HasDatabaseName("IX_MemberRoles_Role_IsActive");

                    b.ToTable("MemberRoles", "membership");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EmployerCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerCode")
                        .HasDatabaseName("IX_Roles_EmployerCode");

                    b.HasIndex("EmployerName")
                        .HasDatabaseName("IX_Roles_EmployerName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Roles_IsActive");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Key");

                    b.HasIndex("SortOrder", "Title")
                        .HasDatabaseName("IX_Roles_SortOrder_Title");

                    b.ToTable("Roles", "membership");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.Member", b =>
                {
                    b.OwnsOne("Nezam.Refahi.Membership.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("MemberId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Members", "membership");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("Nezam.Refahi.Membership.Domain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("MemberId");

                            b1.HasIndex("FirstName");

                            b1.HasIndex("LastName");

                            b1.ToTable("Members", "membership");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.NationalId", "NationalCode", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NationalCode");

                            b1.HasKey("MemberId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_Members_NationalCode");

                            b1.ToTable("Members", "membership");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.OwnsOne("Nezam.Refahi.Shared.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("MemberId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Members", "membership");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("NationalCode")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.MemberAgency", b =>
                {
                    b.HasOne("Nezam.Refahi.Membership.Domain.Entities.Member", "Member")
                        .WithMany("Agencies")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.MemberCapability", b =>
                {
                    b.HasOne("Nezam.Refahi.Membership.Domain.Entities.Member", "Member")
                        .WithMany("Capabilities")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.MemberRole", b =>
                {
                    b.HasOne("Nezam.Refahi.Membership.Domain.Entities.Member", "Member")
                        .WithMany("Roles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nezam.Refahi.Membership.Domain.Entities.Role", "Role")
                        .WithMany("MemberRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.Member", b =>
                {
                    b.Navigation("Agencies");

                    b.Navigation("Capabilities");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Nezam.Refahi.Membership.Domain.Entities.Role", b =>
                {
                    b.Navigation("MemberRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
